### ISSUE TITLE
Uknown Error - Spatial Data Analysis Section

### ISSUE THREAD

**Issue by sarahgeargeoura** [LandSciTech/ccviR#86]
Hello, 

When I enter the shapefiles in the "spatial data analysis" section and click "run", the following error message appears:

"Evaluation error: TopologyException: Input geom 0 is invalid: Self-intersection at 1982189.081570985 317400.88849930477."

I can't seem to attach screenshots but if they are needed, I will send them in an email!

Thank you,
Sarah

**Comment by see24** [comment]
I was getting a slightly different error message but I have fixed it now and the app runs fine with your data now. Please re-install with `remotes::install_github("LandSciTech/ccviR")` and try it now. I am going to close the issue but if it doesn't work you can re-open it.

**Comment by sarahgeargeoura** [comment]
Hi Sarah,

I am not sure why I am still getting the same error message after re-installing the app. 
- Evaluation error: TopologyException: Input geom 0 is invalid: Self-intersection at 1982189.081570985 317400.88849930477.

Is there something I could do on my end to fix it?

Thank you,
Sarah

**Comment by see24** [comment]
Hmm it might be that I was using different climate data. Were you using the one from google drive here https://drive.google.com/file/d/1U6iVI60NvpFY_0cfnpe3gNw2Xpg66sJ4/view?usp=sharing ? 

I will try again with that

**Comment by sarahgeargeoura** [comment]
Let me double check that I am using the right climate data!

**Comment by see24** [comment]
Ok ya please do. When I used the one that is on drive it worked. But if that fixes the problem can you send me the data that did cause the problem?  I would like to address it as well

**Comment by sarahgeargeoura** [comment]
Yes, it worked! I will send you the climate data I was using now!

**Comment by see24** [comment]
I got it to work with the old climate data you were using. Thanks for helping me find these weird cases where issues come up
